name: Code Analyzer

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches-ignore:
      - 'main'

jobs:
  code-style-checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ðŸ“– Get Node Version from .nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: ðŸ“¦ Install dependencies
        run: yarn install

      - name: ðŸ‘€ Checking code style
        run: yarn code:check
  testing-code-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ðŸ“– Get Node Version from .nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: ðŸ“¦ Install dependencies
        run: yarn install

      - name: ðŸ‘€ Tests
        run: yarn test:coverage
